import { mockMultimodalData } from "@/lib/mocks/multimodal";
import type {
  AudioAnalysis,
  ImageAnalysis,
  MediaAnalysis,
  MediaKind,
  MultimodalWorkspaceData,
  VideoAnalysis,
} from "@/types/multimodal";

const allowedTypes: Record<string, MediaKind> = {
  "image/jpeg": "image",
  "image/png": "image",
  "image/webp": "image",
  "video/mp4": "video",
  "video/webm": "video",
  "audio/mpeg": "audio",
  "audio/wav": "audio",
  "audio/ogg": "audio",
};

function delay(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted)
      return reject(new DOMException("Aborted", "AbortError"));
    const timer = window.setTimeout(resolve, ms);
    signal?.addEventListener(
      "abort",
      () => {
        window.clearTimeout(timer);
        reject(new DOMException("Aborted", "AbortError"));
      },
      { once: true },
    );
  });
}

export function mediaKindFor(file: File): MediaKind | null {
  return allowedTypes[file.type] ?? null;
}

export const multimodalService = {
  async getWorkspace(signal?: AbortSignal): Promise<MultimodalWorkspaceData> {
    await delay(360, signal);
    return mockMultimodalData;
  },

  async processDemo(file: File, signal?: AbortSignal): Promise<MediaAnalysis> {
    await delay(1_050, signal);
    const kind = mediaKindFor(file);
    if (!kind) throw new Error("Unsupported media format.");
    if (kind === "image") {
      return {
        kind: "image",
        objects: ["demo subject", "editorial background", "brand-safe region"],
        ocr: ["Sample OCR from demo processing", file.name],
        entities: ["Demo entity", "Agbofa Nexus"],
        authenticity: 86,
        confidence: 89,
        metadata: {
          fileName: file.name,
          size: `${(file.size / 1_048_576).toFixed(2)} MB`,
          processing: "Frontend demo only",
        },
      } satisfies ImageAnalysis;
    }
    if (kind === "video") {
      return {
        kind: "video",
        transcript:
          "Sample transcript generated by frontend demo processing. No media was uploaded to an AI provider.",
        scenes: 6,
        keyframes: [
          "Opening frame",
          "Speaker frame",
          "Data frame",
          "Closing frame",
        ],
        entities: ["Demo speaker", "Sample event"],
        durationSeconds: 94,
        confidence: 84,
      } satisfies VideoAnalysis;
    }
    return {
      kind: "audio",
      transcript:
        "Sample transcript generated locally for interface demonstration. Backend integration is pending.",
      speakers: 2,
      language: "English · demo classification",
      durationSeconds: 128,
      confidence: 82,
    } satisfies AudioAnalysis;
  },
};
