apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agbofa-service.name" . }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agbofa-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "agbofa-service.name" . }}
    spec:
      serviceAccountName: {{ include "agbofa-service.name" . }}
      securityContext:
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
      containers:
        - name: service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.service.ports.health }}
            - name: grpc
              containerPort: {{ .Values.service.ports.grpc }}
            - name: metrics
              containerPort: {{ .Values.service.ports.metrics }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.security.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
