import os, re, glob
from pathlib import Path

PROTO_DIR = Path("api/protobuf")
OUT_DIR = Path("packages/api-client/src/gen")

type_map = {
    "string": "string",
    "int32": "number",
    "int64": "number",
    "uint32": "number",
    "uint64": "number",
    "float": "number",
    "double": "number",
    "bool": "boolean",
    "bytes": "Uint8Array",
    "google.protobuf.Timestamp": "string",
    "google.protobuf.Struct": "Record<string, any>",
    "google.protobuf.Any": "any"
}

def clean_type(t):
    t = t.strip()
    if t in type_map:
        return type_map[t]
    if "." in t:
        return t.split(".")[-1]
    return t

def parse_proto(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Remove comments
    content = re.sub(r'//.*', '', content)
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)

    messages = []
    enums = []
    services = []

    # Parse enums
    for m in re.finditer(r'enum\s+(\w+)\s*\{([^}]*)\}', content):
        name = m.group(1)
        body = m.group(2)
        vals = []
        for line in body.splitlines():
            line = line.strip()
            if not line: continue
            parts = line.split("=")
            if len(parts) >= 1:
                vals.append(parts[0].strip())
        enums.append((name, vals))

    # Parse messages
    for m in re.finditer(r'message\s+(\w+)\s*\{([^}]*)\}', content):
        name = m.group(1)
        body = m.group(2)
        fields = []
        for line in body.splitlines():
            line = line.strip()
            if not line or line.startswith("message ") or line.startswith("enum ") or line == "}" or line.startswith("oneof "):
                continue
            # match field: optional/repeated type name = num;
            match = re.match(r'^(optional|repeated)?\s*([\w\.]+)\s+(\w+)\s*=\s*\d+.*;', line)
            if match:
                mod, ftype, fname = match.groups()
                ts_type = clean_type(ftype)
                if mod == "repeated":
                    ts_type += "[]"
                fields.append((fname, ts_type, mod == "optional"))
        messages.append((name, fields))

    # Parse services
    for m in re.finditer(r'service\s+(\w+)\s*\{([^}]*)\}', content):
        name = m.group(1)
        body = m.group(2)
        rpcs = []
        for match in re.finditer(r'rpc\s+(\w+)\s*\(([^)]+)\)\s*returns\s*\(([^)]+)\)', body):
            rpc_name, req_type, res_type = match.groups()
            req_type = req_type.replace("stream ", "").strip().split(".")[-1]
            res_type = res_type.replace("stream ", "").strip().split(".")[-1]
            rpcs.append((rpc_name, req_type, res_type))
        services.append((name, rpcs))

    return enums, messages, services

def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    proto_files = list(PROTO_DIR.rglob("*.proto"))
    barrel_exports = []

    for pf in proto_files:
        rel = pf.relative_to(PROTO_DIR)
        out_file = OUT_DIR / rel.with_suffix(".ts")
        out_file.parent.mkdir(parents=True, exist_ok=True)

        enums, messages, services = parse_proto(pf)
        lines = [
            "// Auto-generated by stephenh-ts-proto compatible generator from " + str(rel),
            "// Do not edit directly",
            ""
        ]

        for name, vals in enums:
            lines.append(f"export type {name} = " + " | ".join([f'"{v}"' for v in vals]) + ";")
            lines.append("")

        for name, fields in messages:
            lines.append(f"export interface {name} {{")
            for fname, ftype, opt in fields:
                q = "?" if opt else ""
                lines.append(f"  {fname}{q}: {ftype};")
            lines.append("}")
            lines.append("")

        for name, rpcs in services:
            lines.append(f"export interface {name}Client {{")
            for rpc_name, req_type, res_type in rpcs:
                lines.append(f"  {rpc_name[0].lower() + rpc_name[1:]}(request: {req_type}, metadata?: Record<string, string>): Promise<{res_type}>;")
            lines.append("}")
            lines.append("")

        with open(out_file, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        export_path = "./" + str(rel.with_suffix("")).replace("\\", "/")
        barrel_exports.append(f'export * from "{export_path}";')

    with open(OUT_DIR / "index.ts", "w", encoding="utf-8") as f:
        f.write("// Barrel export for all generated protobuf TypeScript clients\n" + "\n".join(sorted(barrel_exports)) + "\n")

    print(f"Generated {len(proto_files)} TypeScript protobuf files in {OUT_DIR}")

if __name__ == "__main__":
    main()
