ALTER TABLE authorization_audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE role_policies NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS refresh_tokens_isolation ON refresh_tokens;
ALTER TABLE refresh_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE refresh_tokens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenants_isolation ON tenants;
ALTER TABLE tenants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
